name: Continuos Delivery
on:
  push:
    branches:
      - main #ou qualquer branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuos Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: | # **.py para todos os py
            **.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver # rodar primeiro o deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado.zip
      - name: Display structure of downloaded files
        run: ls -R
